name = "brainwave"
compatibility_date = "2024-03-29"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"


kv_namespaces = [
	{ binding = "CANVAS_SNAPS", id = "b2db91edd08041caa7ffc8e9e6ae94fe" },
	{ binding = "RECOMMENDATIONS", id = "bcae73c2b93841048d0e237b2d7291d8" }
]

env.production.kv_namespaces = [
	{ binding = "CANVAS_SNAPS", id = "b2db91edd08041caa7ffc8e9e6ae94fe" },
	{ binding = "RECOMMENDATIONS", id = "bcae73c2b93841048d0e237b2d7291d8" }
]

[ai]
binding = "AI"

[placement]
mode = "smart"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "brainwave-r2"



[[d1_databases]]
binding = "DATABASE"
database_name = "brainwave-db-preview"
database_id = "8e3e814c-a862-49b4-8294-67967c4d94b4"

[[env.production.d1_databases]]
binding = "DATABASE"
database_name = "brainwave-db-prod"
database_id = "2a51517d-7875-4be5-a5d5-d50d687f87e9"

[env.preview.ai]
binding = "AI"

[[env.preview.d1_databases]]
binding = "DATABASE"
database_name = "brainwave-db-preview"
database_id = "8e3e814c-a862-49b4-8294-67967c4d94b4"

[env.production.ai]
binding = "AI"